# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI

# This will trigger the workflow on any push or pull request
on:
  push:
    branches:
      - '*'  # Trigger on all branches
  pull_request:
    branches:
      - '*'  # Trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the code
      - uses: actions/setup-node@v4  # Set up Node.js environment
        with:
          node-version: 20  # Use Node.js v20
      - run: npm install  # Install dependencies
      - run: npm test  # Run tests
      - run: npm run build  # Build the project

