name: Combined Node.js and Python Workflow

on:
  push:
    branches:
      - '*'  # Trigger on any branch push
  pull_request:
    branches:
      - '*'  # Trigger on any pull request on any branch

jobs:
  node-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]  # Node.js 20 as per latest GitHub Actions defaults

    steps:
    - uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up Node.js
      uses: actions/setup-node@v4  # Updated to latest version
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node.js dependencies
      run: npm install

    - name: Build Node.js project
      run: npm run build

    - name: Run Node.js tests
      run: npm test

    - name: Start Node.js server and test
      run: |
        npm start &
        sleep 5
        curl -f http://localhost:3000 || (echo "Node.js app failed to start" && exit 1)

  python-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up Python 3.10
      uses: actions/setup-python@v4  # Updated to the latest version
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint Python code with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test Python code with pytest
      run: pytest
